name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Java JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Compilar y ejecutar pruebas
        run: mvn clean test
      - name: Empaquetar aplicación
        run: mvn clean package -DskipTests
      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Construir y subir imagen Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: pintoduoc/fullstack3-user-service:latest
